version: "3.2"

services:
  csgo:
    image: crazymax/csgo-server-launcher:latest
    container_name: csgo
    ports:
      - target: 27015
        published: 27015
        protocol: udp
      - target: 27015
        published: 27015
        protocol: tcp
    env_file:
      - "./csgo-server-launcher.env"
    volumes:
      - "./csgo:/var/steamcmd/games/csgo"
      - "./steam:/home/steam/Steam"
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
